// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlJihklXmFUovBH9v-kzp9B1aZtGA9jlY',
    appId: '1:587585105590:web:cddea10aa40d8fdfa80017',
    messagingSenderId: '587585105590',
    projectId: 'restaurantpos-f700a',
    authDomain: 'restaurantpos-f700a.firebaseapp.com',
    storageBucket: 'restaurantpos-f700a.firebasestorage.app',
    measurementId: 'G-SXGD0XKYHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4HiUzvOfrFDtflWm1dGUdD9bSuuOd1fc',
    appId: '1:587585105590:android:b81f930bdbd2fb56a80017',
    messagingSenderId: '587585105590',
    projectId: 'restaurantpos-f700a',
    storageBucket: 'restaurantpos-f700a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmgmi6-VuEbyRd6h2FaHF-4HTGTcPPXgQ',
    appId: '1:587585105590:ios:de4a5caaa0507844a80017',
    messagingSenderId: '587585105590',
    projectId: 'restaurantpos-f700a',
    storageBucket: 'restaurantpos-f700a.firebasestorage.app',
    iosBundleId: 'com.example.restaurantpos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmgmi6-VuEbyRd6h2FaHF-4HTGTcPPXgQ',
    appId: '1:587585105590:ios:de4a5caaa0507844a80017',
    messagingSenderId: '587585105590',
    projectId: 'restaurantpos-f700a',
    storageBucket: 'restaurantpos-f700a.firebasestorage.app',
    iosBundleId: 'com.example.restaurantpos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlJihklXmFUovBH9v-kzp9B1aZtGA9jlY',
    appId: '1:587585105590:web:727cb298804bc775a80017',
    messagingSenderId: '587585105590',
    projectId: 'restaurantpos-f700a',
    authDomain: 'restaurantpos-f700a.firebaseapp.com',
    storageBucket: 'restaurantpos-f700a.firebasestorage.app',
    measurementId: 'G-5MNF5PC3GJ',
  );
}
